Uploaded a plugin for drawing lines
jimp-dev/jimp pull request #908
Opened 2020-07-11 19:14 UTC by BestDr

### What's new?
Added two different methods for drawing multiple kinds of lines, both two methods have different algorithms for the optimization of lines in order to make them not look "so pixelated", users can choose which algorithm to use, but the wuDrawLine is more recommended because I didn't check all cases in the drawLine methods.

### What's next?
- Adding more methods for drawing triangles (you can draw triangles now by drawing multiple lines, but I will be making a separate method for triangles)
- Adding methods for drawing rectangles
- Adding more complicated geometric shapes.

2020-07-11 19:15 UTC, BestDr commented
This pull request is related to #699

2023-02-03 20:27 UTC, hipstersmoothie requested changes

2023-02-03 20:27 UTC, hipstersmoothie commented on packages/plugin-line/src/package-lock.json
> +{
it shouldn't have this

2023-02-03 20:27 UTC, hipstersmoothie commented on packages/plugin-line/src/index.js
> +// });
remove this

2023-02-03 20:27 UTC, hipstersmoothie commented on packages/plugin-line/src/package.json
> +{
Match the style in other plugins

2023-02-03 20:27 UTC, hipstersmoothie commented on packages/plugin-line/src/test.js
> +import jimp =
Add real test

2023-02-06 05:41 UTC, closed without merging